GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

GET http://localhost:3000/users/200

###

POST http://localhost:3000/users
Content-type: application/json

{
    "id": 5,
    "name": "Anna Appelgren",
    "age": "65",
    "gebder": "female"
}

###

DELETE http://localhost:3000/users/4

###

PUT http://localhost:3000/users/2
Content-type: application/json

{
    "name": "Lisa Johansson",
    "age": "32",
    "gender": "female"
}