GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

###

GET http://localhost:3000/users/200

###

POST http://localhost:3000/users
Content-type: application/json

{
    "id": 5,
    "firstname": "Anna",
    "lastname": "Appelgren",
    "age": 65
}

###

DELETE http://localhost:3000/users/2